services:
  sentry_dataset: &sentry
    build:
      dockerfile: sentry.dockerfile
    image: sentry:latest
    dns: 8.8.8.8
    container_name: sentry_dataset
    volumes:
      - /share/sign-ml/torch:/home/torch
      - /share/sign-ml/dataset:/home/dataset
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    command: ["python", "agent_dataset.py", "uoft-cs/cifar10", "16", "1", "dataset/cifar10"]

  sentry_trainer:
    <<: *sentry
    container_name: sentry_trainer
    command: ["python", "agent_trainer.py", "--sig_out", "/home/dataset/cifar10/dataset.sig", "--model_path", "/home/torch", "private-key", "--private_key", "private.pem"]

  sentry_inferencer:
    <<: *sentry
    container_name: sentry_inferencer
    command: ["python", "agent_inferencer.py", "--sig_path", "/home/dataset/cifar10/dataset.sig", "--model_path", "/home/torch", "private-key", "--public_key", "public.pem"]
