services:
  sentry:
    build:
      dockerfile: sentry.dockerfile
    image: sentry:latest
    # ipc: "host"
    # network_mode: "host"
    # cap_add:
    #   - IPC_LOCK
    # devices:
      # - "/dev/infiniband/rdma_cm"
      # - "/dev/infiniband/uverbs*"
      # - "/dev/nvidia-fs*"
    container_name: sentry
    volumes:
      - /share/sign-ml/torch:/home/torch
      - /share/sign-ml/dataset:/home/dataset
      # - /run/udev:/run/udev:ro
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
