services:
  sentry_dataset: &sentry
    build: .
    image: sentry:latest
    ulimits:
      nofile:
        soft: "4096"
        hard: "4096"
    dns: 8.8.8.8
    container_name: sentry_dataset
    volumes:
      - ./signatures:/home/signatures
      - /share/sign-ml/torch:/home/torch
      - /share/sign-ml/dataset:/home/dataset
      - /run/udev:/run/udev:ro
    devices:
      - /dev/nvme0n1p4:/dev/nvme0n1p4
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
    command: >
      python agent_dataset.py uoft-cs/cifar10 16 1 dataset/cifar10

  sentry_trainer:
    <<: *sentry
    container_name: sentry_trainer
    command: >
      python agent_trainer.py --sig_out /home/signatures
      --model_path /home/torch private-key --private_key private.pem

  sentry_inferencer:
    <<: *sentry
    container_name: sentry_inferencer
    command: >
      python agent_inferencer.py --sig_path /home/signatures
      --model_path /home/torch private-key --public_key public.pem

# docker compose cp sentry_trainer:/home/cufile.log .
