services:
  sentry:
    build:
      dockerfile: sentry.dockerfile
    image: sentry:latest
    container_name: sentry
    volumes:
      - /share/sign-ml/torch:/home/torch
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
